### ISSUE TITLE
additional features for the *capu::String* class

### ISSUE THREAD

**Issue by peterpedron** [bmwcarit/capu#21]
Hey guys, I have some ideas for extending the functionality of *capu::String*:

- String tokenizer 
e.g. a method  _capu::List\<capu::String\> tokenize(capu::String token)_ offered by capu::String
- Number<-> String conversion (atm itoa and atoi must be used afaik)
- An _EndsWith_ method in StringUtils, since StartsWith is implemented already!!!

**Comment by veithm** [comment]
endsWith is implemented.
