### ISSUE TITLE
Date & Time Support

### ISSUE THREAD

**Issue by TimoL** [bmwcarit/capu#25]
A cross platform solution for getting date and time information would be great.
This is e.g. useful for writing logs or dumps with timestamps.

I currently use this code for Win & Linux:

<pre>
#include &lt;time.h&gt; // for date and (wall-clock-)time

time_t nowRaw = time(0);
struct tm* now;
now = localtime(&nowRaw);
</pre>

Bonus points for getting time string in user-defined format, e.g.
<pre>
const Timestamp ts = getCurrentDateAndTime();
const String& result = timeToString("dd.mm.yy hh:mm", &ts);
// result is now "13.08.30 08:50"
</pre>

timeToString could interpret 2nd argument = NULL as "use current time"
<pre>
const String& now = timeToString("yyyy_mm_dd_hh_mm_ss", NULL);
// result is now "2013_08_30_08_50_05"
</pre>

Of course, better names would be great, I used this longish names just for illustrating my issue.

I (currently) don''t require it, but next question could be:
* how about calculating with Timestamps?

**Comment by veithm** [comment]
The class Time and Timestamp do provide this functionality.
