### ISSUE TITLE
Selective export of header files

### ISSUE THREAD

**Issue by astreube** [bmwcarit/capu#35]
When creating the deliverable for a platform abstraction only header files required for this abstraction should be included. For example the deliverable for iPhoneOS_ARM64 should only include headers for Generic / Posix / iPhoneOS and iPhoneOS/ARM64. Header files for Android / Linux / Windows / etc. should not be included.

**Comment by veithm** [comment]
With CAPU 0.19.0 this is provided by executing the install target. The install target only installes the required headers for the given platform.
